### ISSUE TITLE
Remarques sur le front [in progress]

### ISSUE THREAD

**Issue by guersbru** [guersbru/alfred#107]
Bruno
- [x] beaucoup d'espace dans la colonne prio
- [x] le hover sur les news est bleu
- [x] le bouton déconnexion à planquer
- [ ] scroll sur la partie news/agenda (par défaut on voit pas tout)
- [x] mettre les bons intitulés sous la barre de quote dans data/quote
![image](https://user-images.githubusercontent.com/7116288/55148642-e2700c80-5148-11e9-9d68-b7b59202af8b.png)

Point de vue perso
- [x] la couleur de fleche de jauge est pas criante pour meta/ebldt pourquoi pas mettre la jauge elle même en couleur ? 
- [x] la colonne news / agenda est hyper large sur mon écran
- [x] le camembert est un peu petit dans sa zone
- [x] les meta à gauche sont un peu comprimées les unes au dessus des autres
![image.png](https://images.zenhubusercontent.com/5a0963138a75884b90872409/56ba7952-f555-4a7d-8748-702fb57629db)
![image.png](https://images.zenhubusercontent.com/5a0963138a75884b90872409/1402ee81-4b1e-44aa-80c1-5accbf863b56)
Anne
- [x] dossiers opérationnels > bien prendre les mêmes catés que sur le design ( ---, PKU, DEP, ARR et pas ---, DEP, DEL)
- [x] LeMans => Le Mans
- [x] mettre les valeurs de claims/quotes à N/A
- [ ] vérifier que l'on a bien la même police partout, elle a un doute
- [x] pas prioritaire = en version desktop les effectifs chevauchent le nombre de dossiers en cours (elle est en chrome, bizarre je n'ai pas le problème de mon côté)
- [x] From to en pays pour ebl list
- [x] check alignement chiffre effectif

Christelle

Tim 
- [x] flèche jauge meta : overlap un peu sur le texte

**Comment by Archymede123** [comment]
- bouton se deconnecter : il ne s'affiche que au hover 
- scroll sur les news : pour moi il faut revoir le design si on veut plus de scroll. 
- meta : pour les petites résolutions (moins de 660px de hauteur), j'ai mis du scroll vertical (solution du lache)
