### ISSUE TITLE
Fuck la police

### ISSUE THREAD

**Issue by guersbru** [guersbru/alfred#143]
@Archymede123
Je me rends compte qu'on a un problème avec la police Nexa sur une partie des composants d'Alfredos. Ce qui est chelou c'est que dès que je clicke sur fontface ninja la police se charge et ça devient beau. J'ai fait un ptit gif pour qu'on se rende compte

![SmTz5Ugkxq](https://user-images.githubusercontent.com/7116288/55541914-3d17e400-56c6-11e9-934a-b4382d31e48c.gif)

**Comment by Archymede123** [comment]
Je reproduis le problème sur safari, j'ai l'impression que c'est Nexa qui bug car NexaBold marche bien. J'ai mis Roboto en fallback pour avoir une police qui s'approche un peu plus de Nexa.
